### ISSUE TITLE
Randomization function

### ISSUE THREAD

**Issue by SapphicCode** [Pandentia/pride#11]
To ease implementation, since we can't directly hook into flags inline, we should have some form of randomization engine. I'm thinking ~~seeding~~ `crypto/rand` ~~with the current unix time in nanoseconds~~, and then grabbing a flag from the `pride.Flags` mapping, perhaps printing its name before printing the flag.

Edit: nevermind, `crypto/rand` seeds itself, I was thinking of `math/rand`. Same effect.

**Comment by cainwatson** [comment]
@Pandentia I'd like to help on this. When/where would this randomization take place? I understand currently if I build and execute the command I can see flags through `./pride <identity>`. Is this suggesting having a random flag show up when you run the command without an identity or something different?

**Comment by SapphicCode** [comment]
I was thinking something like `pride.PrintRandomFlag()`, which could then be implemented by applications down the line that don't want to implement a function for every flag we support, but would rather just like to support all flags that this library provides.

In pseudocode, perhaps [something like this](https://stackoverflow.com/questions/23482786/get-an-arbitrary-key-item-from-a-map/41886299#41886299) across the `pride.Flags` mapping, calling the one that wins out at the end.
